/*******************************************************************************
*   Project      : S32M27xEVB_BLDC_6step_sensorless
*   Revision     : 1.0
*   RTD Version  : 7.0.0
*   Brief description  :
*   File contains definition of functions needed for inverter voltage control.
*
*   Copyright 2025 NXP
*
*   NXP Proprietary. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
*******************************************************************************/
/******************************************************************************
 * actuate_S32m.c
 *
 * rev 1.0 Initial release
 *
 ********************************************************************************/
/******************************************************************************
| Includes
-----------------------------------------------------------------------------*/
#include "actuate_s32m.h"
#include "gflib.h"
#include "gdflib.h"
#include "gmclib.h"
#include "Emios_Mcl_Ip_Sa_PBcfg.h"
#include "Lcu_Ip.h"

/*==================================================================================================
*                                    FUNCTIONS DEFINITION
==================================================================================================*/

/**************************************************************************//*!
@brief Unmask PWM output and set 50% dutycyle

@param[in,out]  

@return
******************************************************************************/

/*FUNCTION**********************************************************************
 *
 * Function Name : ACTUATE_EnableOutput
 * Description   : It unmasks PWM output and set 1% dutycyle.
 *
 *END**************************************************************************/
tBool ACTUATE_EnableOutput(void)
{
    tBool statePWM;
    Lcu_Ip_SyncOutputValueType lcuEnable[6U];
    /* Apply 0.01 duty cycle */
    statePWM = ACTUATE_SetDutycycleAndTrigger(0.01F,0.05F);
    lcuEnable[0].LogicOutputId = LCU_LOGIC_OUTPUT_0;
    lcuEnable[0].Value = 1U;
    lcuEnable[1].LogicOutputId = LCU_LOGIC_OUTPUT_1;
    lcuEnable[1].Value = 1U;
    lcuEnable[2].LogicOutputId = LCU_LOGIC_OUTPUT_2;
    lcuEnable[2].Value = 1U;
    lcuEnable[3].LogicOutputId = LCU_LOGIC_OUTPUT_3;
    lcuEnable[3].Value = 1U;
    lcuEnable[4].LogicOutputId = LCU_LOGIC_OUTPUT_4;
    lcuEnable[4].Value = 1U;
    lcuEnable[5].LogicOutputId = LCU_LOGIC_OUTPUT_5;
    lcuEnable[5].Value = 1U;
    Lcu_Ip_SetSyncOutputEnable(lcuEnable, 6U);

    return (statePWM);
}


/*FUNCTION**********************************************************************
 *
 * Function Name : ACTUATE_DisableOutput
 * Description   : It masks PWM output and set 1% dutycyle.
 *
 *END**************************************************************************/
tBool ACTUATE_DisableOutput(void)
{
    tBool statePWM;
    Lcu_Ip_SyncOutputValueType lcuDisable[6U];
    lcuDisable[0].LogicOutputId = LCU_LOGIC_OUTPUT_0;
    lcuDisable[0].Value = 0U;
    lcuDisable[1].LogicOutputId = LCU_LOGIC_OUTPUT_1;
    lcuDisable[1].Value = 0U;
    lcuDisable[2].LogicOutputId = LCU_LOGIC_OUTPUT_2;
    lcuDisable[2].Value = 0U;
    lcuDisable[3].LogicOutputId = LCU_LOGIC_OUTPUT_3;
    lcuDisable[3].Value = 0U;
    lcuDisable[4].LogicOutputId = LCU_LOGIC_OUTPUT_4;
    lcuDisable[4].Value = 0U;
    lcuDisable[5].LogicOutputId = LCU_LOGIC_OUTPUT_5;
    lcuDisable[5].Value = 0U;
    Lcu_Ip_SetSyncOutputEnable(lcuDisable, 6U);

    InputSector[0].Value = 1U;
    InputSector[1].Value = 1U;
    InputSector[2].Value = 1U;
    Lcu_Ip_SetSyncInputSwOverrideValue(InputSector, 4U);
    /* Apply 0.01 duty cycle */
    statePWM = ACTUATE_SetDutycycleAndTrigger(0.01F,0.05F);
    
    return (statePWM);
}

/*FUNCTION**********************************************************************
 *
 * Function Name : ACTUATE_SetDutycycle
 * Description   : It sets PWM dutycyle, the dutycyle will by updated on next reload event.
 *
 *END**************************************************************************/
tBool ACTUATE_SetDutycycleAndTrigger(tFloat fltpwm, tFloat flttrigger)
{
    tBool statePwm = TRUE;
    /*pwm timebase period generated by config tool*/
    uint16 pwmPeriodHalf =(uint16) (Emios_Mcl_Ip_Sa_0_MasterBusConfig[0].defaultPeriod >> 1);
    float pwmPeriod =(float) Emios_Mcl_Ip_Sa_0_MasterBusConfig[0].defaultPeriod;
    uint16 triggerRegA= ((uint16_t)(flttrigger * pwmPeriod))+pwmPeriodHalf;
    uint16 triggerRegB= triggerRegA+5U;
    uint16 pwmShiftA = (pwmPeriodHalf - (uint16_t)((fltpwm) * (float)pwmPeriodHalf));
    uint16 pwmDutyA= (uint16_t)((fltpwm) * (float)pwmPeriod);


    Emios_Mcl_Ip_ComparatorTransferDisable(0U,(uint32_t)0b110U);

    Emios_Pwm_Ip_UpdateUCRegA(0U, 1U, pwmShiftA);
    Emios_Pwm_Ip_UpdateUCRegB(0U, 1U, pwmShiftA+pwmDutyA);

    Emios_Pwm_Ip_UpdateUCRegA(0U, 2U, triggerRegA);
    Emios_Pwm_Ip_UpdateUCRegB(0U, 2U, triggerRegB);

    Emios_Mcl_Ip_ComparatorTransferEnable(0U,(uint32_t)0b110U);

    return (statePwm);
}
